### PR TITLE
Fix datepicker date constraints

### LINKED ISSUE #641: Datepicker date constraints are not working
Dates outside the constraints should not be select-able.

### PR DESCRIPTION
**Pull request by kitsook**
- define attributes for datepicker components to limit the min and max
date
- set default date as empty when creating a new assignment

Closes #641

### CODE REVIEW

File: compair/static/modules/assignment/assignment-module_spec.js [hunk 1]
```diff
@@ -1207,6 +1207,22 @@ describe('assignment-module', function () {
                     $rootScope.assignment = angular.copy(mockAssignment);
                     $rootScope.assignment.id = undefined;
                     $rootScope.assignment.availableCheck = true;
+                    if ($rootScope.date.astart.date == null) {
```
Comment (andrew-gardener) [inline compair/static/modules/assignment/assignment-module_spec.js]: suggest you just set the value instead of using if conditions in tests (the if should always pass/fail since the state should be known and consistent so the if isn't really needed)

**Comment by kitsook** [comment]
@andrew-gardener revised.  pls review. thx

**Comment by kitsook** [comment]
Added checking for empty date.  Also revised test cases.
