### PR TITLE
Fix CSS hiding items incorrectly

### LINKED ISSUE #720: Only one comparison shown under "Your Comparisons"
Problem with the current master branch at 49fa5ff.  Under the "Your Comparisons" tab, only one comparison is shown even when the student completed multiple comparisons.

Seems to be suppressed by CSS.

https://github.com/ubc/compair/blob/49fa5ff2fadc0d58872f6140ce50d90304bd738c/compair/static/less/assignment.less#L201-L203

image

### PR DESCRIPTION
**Pull request by kitsook**
- Remove the `display: none` CSS of `each-evaluation`.  This class is
used in multiple places
- Separate `ng-repeat` and `ng-class` in two separate `div`s to avoid
duplicate entries shown. So no need to use the CSS hack mentioned above.
- Fix the issue of momentary highlight not working. Change to use pure
CSS instead of `$timeout` function

Closes #720

### CODE REVIEW

File: compair/static/modules/assignment/assignment-module.js [hunk 1]
```diff
@@ -909,13 +909,8 @@ module.controller("AssignmentViewController",
         // Highlight the answer if it's in the URL
         $scope.highlightAnswer = $location.search().highlightAnswer;
         if ($scope.highlightAnswer) {
-
-            $location.hash('my-answer');
+            $location.hash('answers');
             $anchorScroll();
-
-            $timeout(function() {
-                $('#my-answer').addClass('highlight-off');
```
Comment (andrew-gardener) [inline compair/static/modules/assignment/assignment-module.js]: Since there is no more `highlight-off` class, can you add `$scope.highlightAnswer = undefined;` in the `setTab` function (so the answer will not re-highlight when switching tabs)
