### PR TITLE
Misc fixes for assignments and answers

### LINKED ISSUE #699: Instructor labels not displayed on assignment screen
https://github.com/ubc/compair/blob/966729f2db4041d04efa8d64f88c1529d7cf78f5/compair/static/modules/assignment/assignment-view-partial.html#L182

should be 

```
<em>{{instructorLabel(answer.user_id)}} Response</em>
```

### LINKED ISSUE #705: Jump to "Your Feedback" tab after deleting an answer
Found on `master` branch b85f8c12

Steps to reproduce the issue:
- login as instructor to view assignment answer
- click on the `trashcan` icon to delete an answer
- after confirmation, browser attempted to jump to `Your Feedback` tab, which normally isn't available to instructors

### LINKED ISSUE #708: Instructors can't edit student answers
Issue on the master branch b85f8c1

Instructors can't edit student answers.

In master branch, the parameter `user_id` passed in (and thus `user_uuid`) is the instructor ID.  Previously, it was the user id of the answer being edited ~~(which is a bit strange)~~.

EDIT: when instructors edit a student answer, the `user_id` passed in should be the student's id

https://github.com/ubc/compair/blob/b85f8c124ecdc25a8bad8625ba1e95712430df24/compair/api/answer.py#L330-L334

### PR DESCRIPTION
**Pull request by kitsook**
- Fix a label issue of non-comparable instructor answers on assignment
screen. Closes #699
- Fix issue of jumping to "your feedback" tab after instructors deleting
answers. Closes #705
- Fix issue of instructors can't edit student answers. Closes #708

### CODE REVIEW

File: compair/static/modules/answer/answer-module.js [hunk 1]
```diff
@@ -159,7 +159,10 @@ module.controller(
                     $scope.classlist = ret.objects;
                 }
             );
-            $scope.answer.user_id = $scope.loggedInUserId;
+            // only preset user_id when creating new answer
+            if ($scope.method == "create") {
+                $scope.answer.user_id = $scope.loggedInUserId;
```
Comment (andrew-gardener) [inline compair/static/modules/answer/answer-module.js]: Can you instead move it below the object assignment in the other `if ($scope.method == "create")` on line 129. I think it will be easier to keep track of up there

ie:
```
if ($scope.method == "create") {
    $scope.answer = {
        ...
    };
    if ($scope.canManageAssignment) {
        $scope.answer.user_id = $scope.loggedInUserId;
    }
    ...
}
```
